name: focus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

  # utils
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  shimmer: ^3.0.0
  easy_debounce: ^2.0.3
  image: ^4.5.4
  carousel_slider: ^5.1.1
  dio: ^5.9.0

  # local storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  
  # router
  go_router: ^16.1.0

  # Icons
  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # env
    - lib/envs/

  # fonts
  fonts:
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
          style: italic